---
# Install nodejs 

- name: Import Node GPG key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true

- name: Add Repository for filebeat
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present
  become: true

- name: Install filebeat
  apt:
    name: filebeat
    state: present
    update_cache: yes
  become: true

- name: Copy config
  copy:
    src: ../files/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    force: yes
    owner: root
    group: root
    mode: 0600
  become: true

- name: Restart service
  service:
    name: filebeat
    enabled: yes
    state: restarted
  become: true


