---
# 

- name: Install nginx
  apt:
    name: nginx
    state: present
  become: true

- name: Remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Config Mysql
  copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
    force: yes
    owner: root
    group: root
    mode: 0644
  become: true


- name: Config Nodejs
  copy:
    src: ../files/nodejs.conf
    dest: /etc/nginx/sites-enabled/nodejs.conf
    force: yes
    owner: root
    group: root
    mode: 0644
  become: true


- name: Config Elastic
  copy:
    src: ../files/elastic.conf
    dest: /etc/nginx/sites-enabled/elastic.conf
    force: yes
    owner: root
    group: root
    mode: 0644
  become: true


- name: Config Kibana
  copy:
    src: ../files/kibana.conf
    dest: /etc/nginx/sites-enabled/kibana.conf
    force: yes
    owner: root
    group: root
    mode: 0644
  become: true

- name: Restart service
  service:
    name: nginx
    enabled: yes
    state: restarted
  become: true
  
