---
# 

- name: Stop service
  service:
    name: app_{{ app_port }} 
    state: stopped
  ignore_errors: yes
  become: true

- name: Create application folder
  file: path={{ ansible_env.HOME }}/app_{{ app_port }}  state=directory

- name: Copy package.json
  copy:
    src: ../files/package.json
    dest: "{{ ansible_env.HOME }}/app_{{ app_port }}/package.json"
    force: yes
    mode: 0644

- name: Copy status.js
  copy:
    src: ../files/status.js
    dest: "{{ ansible_env.HOME }}/app_{{ app_port }}/status.js"
    force: yes
    mode: 0644

# NPM INSTLAL
- name: Npm install
  npm: path={{ ansible_env.HOME }}/app_{{ app_port }} state=present


# Install as service
- name: Install service for autorun
  shell: "forever-service install app_{{ app_port }} -e 'PORT={{ app_port }} MYSQL=mysql://test:Qwerty123@172.16.0.103/mysql ELASTIC=http://172.16.0.103:9200' --script {{ ansible_env.HOME }}/app_{{ app_port }}/status.js  "
  become: true

# Run
- name: Run service
  service:
    name: app_{{ app_port }} 
    state: started
  become: true

