---
# Main playbook to deploy

- hosts: node1
  roles:
    - java8
    - nodejs
    - { role: deploy, app_port: "10001" }
    - { role: deploy, app_port: "10002" }
    - percona-master
    - elasticsearch
  

- hosts: node2
  roles:
    - java8
    - nodejs
    - { role: deploy, app_port: "10003" }
    - { role: deploy, app_port: "10004" }
    - percona-slave
    - elasticsearch


- hosts: node3
  roles:
    - java8
    - nodejs
    - { role: deploy, app_port: "10005" }
    - nginx
    - logstash
    - kibana



