---
# Main playbook to deploy

# install nodejs and filebeat to the all nodes
- hosts: all
  roles:
    - nodejs
    - filebeat

- hosts: mysql-master
  roles:
    - percona-master

- hosts: mysql-slave
  roles:
    - percona-slave


# install logstash to the node3
- hosts: logstash
  roles:
    - java8
    - logstash

