---
# Main playbook to deploy

# install nodejs and filebeat to the all nodes
- hosts: all
  roles:
    - nodejs
    - filebeat
    - java8

# install master node for percona
- hosts: mysql-master
  roles:
    - percona-master

# install slave node for percona
- hosts: mysql-slave
  roles:
    - percona-slave

# install logstash to the node3
- hosts: logstash
  roles:
    - logstash

# install elastic node
- hosts: all
  roles:
    - elasticsearch

# install kibana
- hosts: kibana
  roles:
    - kibana
