# Hosts for ansible
[all]
node1 ansible_ssh_host=172.16.0.101
node2 ansible_ssh_host=172.16.0.102
node3 ansible_ssh_host=172.16.0.103

[node1]
node1 ansible_ssh_host=172.16.0.101

[node2]
node2 ansible_ssh_host=172.16.0.102

[node3]
node3 ansible_ssh_host=172.16.0.103



