# Hosts for ansible
[mysql-master]
node1 ansible_ssh_host=172.16.0.101

[mysql-slave]
node2 ansible_ssh_host=172.16.0.102

[all]
node1 ansible_ssh_host=172.16.0.101
node2 ansible_ssh_host=172.16.0.102
node3 ansible_ssh_host=172.16.0.103

[nginx]
node3 ansible_ssh_host=172.16.0.103

[elastic]
node1 ansible_ssh_host=172.16.0.101
node2 ansible_ssh_host=172.16.0.102

[logstash]
node3 ansible_ssh_host=172.16.0.103

