# Hosts for ansible
[all]
node1 ansible_ssh_host=172.16.0.101
node2 ansible_ssh_host=172.16.0.102
node3 ansible_ssh_host=172.16.0.103

[mysql-master]
node1 ansible_ssh_host=172.16.0.101


[mysql-slave]
node2 ansible_ssh_host=172.16.0.102

[nginx]
node3 ansible_ssh_host=172.16.0.103

[elasticsearch]
node1 ansible_ssh_host=172.16.0.101
node2 ansible_ssh_host=172.16.0.102
node3 ansible_ssh_host=172.16.0.103

[logstash]
node3 ansible_ssh_host=172.16.0.103

[kibana]
node3 ansible_ssh_host=172.16.0.103


