---
# Install nodejs 

- name: Add Repository for 6.x 
  shell: 'curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -'
  become: true

- name: Install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true
