---
# 

- name: Install Kibana
  apt:
    name: kibana
    state: present
  become: true

- name: Copy config
  copy:
    src: ../files/kibana.yml
    dest: /etc/kibana/kibana.yml
    force: yes
    owner: root
    group: root
    mode: 0644
  become: true


- name: Restart service
  service:
    name: kibana
    enabled: yes
    state: restarted
  become: true
  
