---
# Install percona claster

- name: Install percona-xtradb-cluster-server
  apt:
    name: percona-xtradb-cluster-server
    state: present
    update_cache: yes
  become: true

- name: Stop service
  service:
    name: mysql
    state: stopped
  become: true

- name: Copy cluster config
  copy:
    src: ../files/node1.cnf 
    dest: /etc/mysql/node1.cnf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Create symlinc
  file:
    src: /etc/mysql/node1.cnf
    dest: /etc/mysql/my.cnf
    state: link
    force: yes
  become: true
  

- name: Init cluster
  command: "/etc/init.d/mysql bootstrap-pxc"
  become: true

- name: Install python-mysqldb
  apt: pkg={{ item }} state=present
  with_items:
    - python-mysqldb
  become: true


- name: Create user 
  mysql_user:
    name: 'sstuser'
    host: 'localhost'
    password: Qwerty123
    priv: "*.*:REPLICATION CLIENT"
    state: present
  become: true

- name: Grant Privs 1
  mysql_user:
    name: 'sstuser'
    host: 'localhost'
    append_privs: yes
    priv: "*.*:LOCK TABLES"
    state: present
  become: true

    
- name: Grant Privs 2
  mysql_user:
    name: 'sstuser'
    host: 'localhost'
    append_privs: yes
    priv: '*.*:RELOAD,PROCESS'
    state: present
  become: true

