---
# Install percona claster

- name: Install percona-xtradb-cluster-server
  apt:
    name: percona-xtradb-cluster-server
    state: present
    update_cache: yes
  become: true

- name: Stop service
  service:
    name: mysql
    state: stopped
  become: true

- name: Copy cluster config
  copy:
    src: ../files/node2.cnf 
    dest: /etc/mysql/node2.cnf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Create symlinc
  file:
    src: /etc/mysql/node2.cnf
    dest: /etc/mysql/my.cnf
    state: link
    force: yes
  become: true
  

- name: Start node
  command: "/etc/init.d/mysql start"
  become: true

