---
# 

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
  become: true

- name: Reduce memory for java Xms
  replace:
    dest: /etc/elasticsearch/jvm.options
    regexp: '^-Xms.*$'
    replace: '-Xms128m'
  become: true

- name: Reduce memory for java Xmx
  replace:
    dest: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx.*$'
    replace: '-Xmx128m'
  become: true

- name: Copy config
  copy:
    src: ../files/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    force: yes
    owner: root
    group: elasticsearch
    mode: 0660
  become: true


- name: Restart service
  service:
    name: elasticsearch
    enabled: yes
    state: restarted
  become: true
  
